export const GET_PLANS_REQUEST = 'GET_PLANS_REQUEST';
export const GET_PLANS_SUCCESS = 'GET_PLANS_SUCCESS';
export const GET_PLANS_FAILURE = 'GET_PLANS_FAILURE';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const UPDATE_SUBSCRIPTION_REQUEST = 'UPDATE_SUBSCRIPTION_REQUEST';
export const UPDATE_SUBSCRIPTION_SUCCESS = 'UPDATE_SUBSCRIPTION_SUCCESS';
export const UPDATE_SUBSCRIPTION_FAILURE = 'UPDATE_SUBSCRIPTION_FAILURE';
export const CANCEL_SUBSCRIPTION_REQUEST = 'CANCEL_SUBSCRIPTION_REQUEST';
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_FAILURE = 'CANCEL_SUBSCRIPTION_FAILURE';
export const GET_CUSTOMER_REQUEST = 'GET_CUSTOMER_REQUEST';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_FAILURE = 'GET_CUSTOMER_FAILURE';
export const GET_CUSTOMER_INVOICES_REQUEST = 'GET_CUSTOMER_INVOICES_REQUEST';
export const GET_CUSTOMER_INVOICES_SUCCESS = 'GET_CUSTOMER_INVOICES_SUCCESS';
export const GET_CUSTOMER_INVOICES_FAILURE = 'GET_CUSTOMER_INVOICES_FAILURE';
export const ADD_COUPON_REQUEST = 'ADD_COUPON_REQUEST';
export const ADD_COUPON_SUCCESS = 'ADD_COUPON_SUCCESS';
export const ADD_COUPON_FAILURE = 'ADD_COUPON_FAILURE';
export const EDIT_BILLING_EMAIL_REQUEST = 'EDIT_BILLING_EMAIL_REQUEST';
export const EDIT_BILLING_EMAIL_SUCCESS = 'EDIT_BILLING_EMAIL_SUCCESS';
export const EDIT_BILLING_EMAIL_FAILURE = 'EDIT_BILLING_EMAIL_FAILURE';
export const COUPON_FORM_NAME = 'couponForm';
export const PLAN_INTERVALS = {
    YEAR: 'year',
    MONTH: 'month',
};



// WEBPACK FOOTER //
// ./src/consts/billing.js