export const GET_CONTAINERS = 'GET_CONTAINERS';
export const GET_CONTAINERS_REQUEST = `${GET_CONTAINERS}_REQUEST`;
export const GET_CONTAINERS_SUCCESS = `${GET_CONTAINERS}_SUCCESS`;
export const GET_CONTAINERS_FAILURE = `${GET_CONTAINERS}_FAILURE`;

export const GET_CONTAINER_REQUEST = 'GET_CONTAINER_REQUEST';
export const GET_CONTAINER_SUCCESS = 'GET_CONTAINER_SUCCESS';
export const GET_CONTAINER_FAILURE = 'GET_CONTAINER_FAILURE';
export const GET_LINK_CONTAINER_BY_SIDE_REQUEST = 'GET_LINK_CONTAINER_BY_SIDE_REQUEST';
export const GET_LINK_CONTAINER_BY_SIDE_SUCCESS = 'GET_LINK_CONTAINER_BY_SIDE_SUCCESS';
export const GET_LINK_CONTAINER_BY_SIDE_FAILURE = 'GET_LINK_CONTAINER_BY_SIDE_FAILURE';
export const GET_WORKSPACES_REQUEST = 'GET_WORKSPACES_REQUEST';
export const GET_WORKSPACES_SUCCESS = 'GET_WORKSPACES_SUCCESS';
export const GET_WORKSPACES_FAILURE = 'GET_WORKSPACES_FAILURE';
export const CREATE_CONTAINER_REQUEST = 'CREATE_CONTAINER_REQUEST';
export const CREATE_CONTAINER_SUCCESS = 'CREATE_CONTAINER_SUCCESS';
export const CREATE_CONTAINER_FAILURE = 'CREATE_CONTAINER_FAILURE';
export const CLEAR_CONTAINERS = 'CLEAR_CONTAINERS';

export const GET_CONTAINER_PLUGINS_REQUEST = 'GET_CONTAINER_PLUGINS_REQUEST';
export const GET_CONTAINER_PLUGINS_SUCCESS = 'GET_CONTAINER_PLUGINS_SUCCESS';
export const GET_CONTAINER_PLUGINS_FAILURE = 'GET_CONTAINER_PLUGINS_FAILURE';

export const STATE = {
    INACCESSIBLE: 'inaccessible',
    ACTIVE: 'active',
};



// WEBPACK FOOTER //
// ./src/consts/containers.js