export const ADD_FIELD_ASSOCIATION = 'ADD_FIELD_ASSOCIATION';
export const DELETE_FIELD_ASSOCIATION = 'DELETE_FIELD_ASSOCIATION';
export const ADD_FIELD_ASSOCIATION_GROUP = 'ADD_FIELD_ASSOCIATION_GROUP';
export const ADD_FIELD_ASSOCIATION_ITEM = 'ADD_FIELD_ASSOCIATION_ITEM';
export const UNMAP_FIELD_ASSOCIATION_ITEM = 'UNMAP_FIELD_ASSOCIATION_ITEM';
export const REMOVE_FIELD_ASSOCIATION_GROUP = 'REMOVE_FIELD_ASSOCIATION_GROUP';
export const GET_CUSTOM_FIELDS_REQUEST = 'GET_CUSTOM_FIELDS_REQUEST';
export const GET_CUSTOM_FIELDS_SUCCESS = 'GET_CUSTOM_FIELDS_SUCCESS';
export const GET_CUSTOM_FIELDS_FAILURE = 'GET_CUSTOM_FIELDS_FAILURE';
export const GET_FIELD_VALUE_REQUEST = 'GET_FIELD_VALUE_REQUEST';
export const GET_FIELD_VALUE_SUCCESS = 'GET_FIELD_VALUE_SUCCESS';
export const GET_FIELD_VALUE_FAILURE = 'GET_FIELD_VALUE_FAILURE';
export const GET_FIELD_VALUES_REQUEST = 'GET_FIELD_VALUES_REQUEST';
export const GET_FIELD_VALUES_SUCCESS = 'GET_FIELD_VALUES_SUCCESS';
export const GET_FIELD_VALUES_FAILURE = 'GET_FIELD_VALUES_FAILURE';
export const AUTOMAP_FIELD_VALUES_REQUEST = 'AUTOMAP_FIELD_VALUES_REQUEST';
export const AUTOMAP_FIELD_VALUES_SUCCESS = 'AUTOMAP_FIELD_VALUES_SUCCESS';
export const AUTOMAP_FIELD_VALUES_FAILURE = 'AUTOMAP_FIELD_VALUES_FAILURE';
export const GET_WORKFLOWS_REQUEST = 'GET_WORKFLOWS_REQUEST';
export const GET_WORKFLOWS_SUCCESS = 'GET_WORKFLOWS_SUCCESS';
export const GET_WORKFLOWS_FAILURE = 'GET_WORKFLOWS_FAILURE';
export const GENERATE_FIELD_ASSOCIATIONS = 'GENERATE_FIELD_ASSOCIATIONS';
export const GENERATE_FIELD_ASSOCIATIONS_REQUEST = `${GENERATE_FIELD_ASSOCIATIONS}_REQUEST`;
export const GENERATE_FIELD_ASSOCIATIONS_SUCCESS = `${GENERATE_FIELD_ASSOCIATIONS}_SUCCESS`;
export const GENERATE_FIELD_ASSOCIATIONS_FAILURE = `${GENERATE_FIELD_ASSOCIATIONS}_FAILURE`;
export const MAKE_DEFAULT_FIELD_ASSOCIATION_ITEM = 'MAKE_DEFAULT_FIELD_ASSOCIATION_ITEM';
export const CHANGE_FIELD_ASSOCIATION_TARGET = 'CHANGE_FIELD_ASSOCIATION_TARGET';
export const CREATE_FIELD_VALUE_REQUEST = 'CREATE_FIELD_VALUE_REQUEST';
export const CREATE_FIELD_VALUE_SUCCESS = 'CREATE_FIELD_VALUE_SUCCESS';
export const CREATE_FIELD_VALUE_FAILURE = 'CREATE_FIELD_VALUE_FAILURE';

export const KINDS = {
    PCD_FIELD: 'pcdField',
    PCD_COMMON: 'pcdCommon',
    CUSTOM_FIELD: 'custom',
};

export const FIELD_VALUES_TYPE = {
    BOOLEAN: 'boolean',
    ID: 'id',
    USERS: 'users',
};

export const TARGET = {
    A: 'A',
    B: 'B',
    BOTH: 'both',
};

export const DESCRIPTION_FOOTER = 'linkBlock';



// WEBPACK FOOTER //
// ./src/consts/fields.js