export const GET_ORGANIZATION_INVITES_REQUEST = 'GET_ORGANIZATION_INVITES_REQUEST';
export const GET_ORGANIZATION_INVITES_SUCCESS = 'GET_ORGANIZATION_INVITES_SUCCESS';
export const GET_ORGANIZATION_INVITES_FAILURE = 'GET_ORGANIZATION_INVITES_FAILURE';

export const GET_USER_PENDING_INVITES_REQUEST = 'GET_USER_PENDING_INVITES_REQUEST';
export const GET_USER_PENDING_INVITES_SUCCESS = 'GET_USER_PENDING_INVITES_SUCCESS';
export const GET_USER_PENDING_INVITES_FAILURE = 'GET_USER_PENDING_INVITES_FAILURE';

export const CREATE_INVITE_REQUEST = 'CREATE_INVITE_REQUEST';
export const CREATE_INVITE_FAILURE = 'CREATE_INVITE_FAILURE';
export const CREATE_INVITE_SUCCESS = 'CREATE_INVITE_SUCCESS';

export const UPDATE_INVITE_REQUEST = 'UPDATE_INVITE_REQUEST';
export const UPDATE_INVITE_FAILURE = 'UPDATE_INVITE_FAILURE';
export const UPDATE_INVITE_SUCCESS = 'UPDATE_INVITE_SUCCESS';

export const STATES = {
    PENDING: 'pending',
    ACCEPTED: 'accepted',
    DECLINED: 'declined',
    EXPIRED: 'expired',
    CANCELED: 'canceled',
};

export const INVITE_BY_EMAIL_FORM = 'INVITE_BY_EMAIL_FORM';



// WEBPACK FOOTER //
// ./src/consts/invites.js