/**
 * @name LinkConstants
 * Constants for link module
 */
import {
    OrderedMap
} from 'immutable';

export const ENTITY_NAME = 'links';

export const ADD_LINK = 'ADD_LINK';
export const ADD_LINK_FAILURE = `${ADD_LINK}_FAILURE`;
export const ADD_LINK_REQUEST = `${ADD_LINK}_REQUEST`;
export const ADD_LINK_SUCCESS = `${ADD_LINK}_SUCCESS`;
export const AUTOMAP_USERS_FAILURE = 'AUTOMAP_USERS_FAILURE';
export const AUTOMAP_USERS_REQUEST = 'AUTOMAP_USERS_REQUEST';
export const AUTOMAP_USERS_SUCCESS = 'AUTOMAP_USERS_SUCCESS';
export const DELETE_LINK_FAILURE = 'DELETE_LINK_FAILURE';
export const DELETE_LINK_REQUEST = 'DELETE_LINK_REQUEST';
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS';
export const DIAGNOSE_LINK_FAILURE = 'DIAGNOSE_LINK_FAILURE';
export const DIAGNOSE_LINK_REQUEST = 'DIAGNOSE_LINK_REQUEST';
export const DIAGNOSE_LINK_SUCCESS = 'DIAGNOSE_LINK_SUCCESS';
export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE';
export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST';
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
export const GET_LINKS_SYNC_STATES_FAILURE = 'GET_LINKS_SYNC_STATES_FAILURE';
export const GET_LINKS_SYNC_STATES_REQUEST = 'GET_LINKS_SYNC_STATES_REQUEST';
export const GET_LINKS_SYNC_STATES_SUCCESS = 'GET_LINKS_SYNC_STATES_SUCCESS';
export const GET_LINK_DASHBOARD_FAILURE = 'GET_LINK_DASHBOARD_FAILURE';
export const GET_LINK_DASHBOARD_REQUEST = 'GET_LINK_DASHBOARD_REQUEST';
export const GET_LINK_DASHBOARD_SUCCESS = 'GET_LINK_DASHBOARD_SUCCESS';
export const GET_LINK_FAILURE = 'GET_LINK_FAILURE';
export const GET_LINK_REQUEST = 'GET_LINK_REQUEST';
export const GET_LINK_SUCCESS = 'GET_LINK_SUCCESS';
export const LINK_REVIEW_FAILURE = 'LINK_REVIEW_FAILURE';
export const LINK_REVIEW_REQUEST = 'LINK_REVIEW_REQUEST';
export const LINK_REVIEW_SUCCESS = 'LINK_REVIEW_SUCCESS';
export const SAVE_LINK_FAILURE = 'SAVE_LINK_FAILURE';
export const SAVE_LINK_REQUEST = 'SAVE_LINK_REQUEST';
export const SAVE_LINK_SUCCESS = 'SAVE_LINK_SUCCESS';
export const SET_AUTO_SYNC_LINK_FAILURE = 'SET_AUTO_SYNC_LINK_FAILURE';
export const SET_AUTO_SYNC_LINK_REQUEST = 'SET_AUTO_SYNC_LINK_REQUEST';
export const SET_AUTO_SYNC_LINK_SUCCESS = 'SET_AUTO_SYNC_LINK_SUCCESS';
export const SET_MANUAL_SYNC_LINK_FAILURE = 'SET_MANUAL_SYNC_LINK_FAILURE';
export const SET_MANUAL_SYNC_LINK_REQUEST = 'SET_MANUAL_SYNC_LINK_REQUEST';
export const SET_MANUAL_SYNC_LINK_SUCCESS = 'SET_MANUAL_SYNC_LINK_SUCCESS';
export const START_SYNC_LINK = 'START_SYNC_LINK';
export const SYNC_LINK_FAILURE = 'SYNC_LINK_FAILURE';
export const SYNC_LINK_REQUEST = 'SYNC_LINK_REQUEST';
export const SYNC_LINK_SUCCESS = 'SYNC_LINK_SUCCESS';
export const GET_TASK_SYNC_TASK_COUNT_REQUEST = 'GET_TASK_SYNC_TASK_COUNT_REQUEST';
export const GET_TASK_SYNC_TASK_COUNT_FAILURE = 'GET_TASK_SYNC_TASK_COUNT_FAILURE';
export const GET_TASK_SYNC_TASK_COUNT_SUCCESS = 'GET_TASK_SYNC_TASK_COUNT_SUCCESS';

export const CHANGE_ALL_FIELD_ASSOCIATION_TARGET = 'CHANGE_ALL_FIELD_ASSOCIATION_TARGET';
export const EDIT_LINK = 'EDIT_LINK';
export const PAUSE_SYNC_LINK = 'PAUSE_SYNC_LINK';
export const REMOVE_FIELD_ASSOCIATION_GROUP = 'REMOVE_FIELD_ASSOCIATION_GROUP';
export const RESET_DIAGNOSTIC = 'RESET_DIAGNOSTIC';
export const UPDATE_FIELD_ASSOCIATION_VALUE_MAPPING = 'UPDATE_FIELD_ASSOCIATION_VALUE_MAPPING';
export const UPDATE_NEW_FIELD_ASSOCIATION_VALUE = 'UPDATE_NEW_FIELD_ASSOCIATION_VALUE';
export const ADD_LINK_USER_ACTION = 'ADD_LINK_USER_ACTION';

export const LINK_STATES = {
    ACTIVE: 'active',
    DISABLED: 'disabled',
    DISCONNECTED: 'disconnected',
    DELETED: 'deleted',
    INACCESSIBLE: 'inaccessible',
};
export const LINK_SYNC_STATES = {
    SYNCING: 'syncing',
    IDLE: 'idle',
};

export const DIRECTIONS = OrderedMap({
    BOTH: 'both',
    RIGHT: 'right',
    LEFT: 'left',
});

export const WARNINGS = {
    MISSING_MAPPING_FIELD_VALUE: 'MISSING_MAPPING_FIELD_VALUE',
    NO_FILTERS_MULTI_SYNC_BOTH: 'NO_FILTERS_MULTI_SYNC_BOTH',
    NO_FILTERS_MULTI_SYNC_OTHER_RO: 'NO_FILTERS_MULTI_SYNC_BOTH_OTHER_RO',
    UNMAPPED_STATUSES: 'UNMAPPED_STATUSES',
};

export const DEFAULT_MAPPING_STATE = {
    FAILED: 'FAILED',
    LOADING: 'LOADING',
    LOADED: 'LOADED',
};

export const KIND = {
    MIRROR_SYNC: 'mirrorSync',
    MULTI_SYNC: 'multiSync',
    TASK_SYNC: 'taskSync',
};

export const SOURCE = {
    CONSOLE: 'console',
    TRELLO_POWER_UP_CARD_SYNC: 'trelloPowerUpCardSync',
};



// WEBPACK FOOTER //
// ./src/consts/link.js