/**
 * @name MultisyncConstants
 * Constants for MULTISYNC module
 */

export const ENTITY_NAME = 'multisyncs';
export const ADD_MULTISYNC = 'ADD_MULTISYNC';
export const DELETE_MULTISYNC = 'DELETE_MULTISYNC';
export const GET_MULTISYNC = 'GET_MULTISYNC';
export const SAVE_MULTISYNC = 'SAVE_MULTISYNC';

export const GET_MULTISYNCS_FAILURE = 'GET_MULTISYNCS_FAILURE';
export const GET_MULTISYNCS_REQUEST = 'GET_MULTISYNCS_REQUEST';
export const GET_MULTISYNCS_SUCCESS = 'GET_MULTISYNCS_SUCCESS';

export const GET_MULTISYNC_FAILURE = `${GET_MULTISYNC}_FAILURE`;
export const GET_MULTISYNC_REQUEST = `${GET_MULTISYNC}_REQUEST`;
export const GET_MULTISYNC_SUCCESS = `${GET_MULTISYNC}_SUCCESS`;

export const ADD_MULTISYNC_FAILURE = `${ADD_MULTISYNC}_FAILURE`;
export const ADD_MULTISYNC_REQUEST = `${ADD_MULTISYNC}_REQUEST`;
export const ADD_MULTISYNC_SUCCESS = `${ADD_MULTISYNC}_SUCCESS`;

export const DELETE_MULTISYNC_FAILURE = `${DELETE_MULTISYNC}_FAILURE`;
export const DELETE_MULTISYNC_REQUEST = `${DELETE_MULTISYNC}_REQUEST`;
export const DELETE_MULTISYNC_SUCCESS = `${DELETE_MULTISYNC}_SUCCESS`;

export const SAVE_MULTISYNC_FAILURE = `${SAVE_MULTISYNC}_FAILURE`;
export const SAVE_MULTISYNC_REQUEST = `${SAVE_MULTISYNC}_REQUEST`;
export const SAVE_MULTISYNC_SUCCESS = `${SAVE_MULTISYNC}_SUCCESS`;

export const COPY_DEFAULT_FIELD_ASSOCIATIONS = 'COPY_DEFAULT_FIELD_ASSOCIATIONS';
export const CLEAN_UP_CURRENT_MULTISYNC = 'CLEAN_UP_CURRENT_MULTISYNC';
export const CHANGE_ALL_FIELD_ASSOCIATION_TARGET_MULTISYNC = 'CHANGE_ALL_FIELD_ASSOCIATION_TARGET_MULTISYNC';


export const STATES = {
    ACTIVE: 'active',
    DRAFT: 'draft',
    DELETED: 'deleted',
};

export const TOPOLOGIES = {
    SPLIT: 'split',
    MERGE: 'merge',
};

export const SYNC_DIRECTION = {
    TWO_WAY: 'twoWay',
    ONE_WAY: 'oneWay',
};



// WEBPACK FOOTER //
// ./src/consts/multisync.js