export const GET_ORGANIZATIONS_REQUEST = 'GET_ORGANIZATIONS_REQUEST';
export const GET_ORGANIZATIONS_FAILURE = 'GET_ORGANIZATIONS_FAILURE';
export const GET_ORGANIZATIONS_SUCCESS = 'GET_ORGANIZATIONS_SUCCESS';

export const GET_COLLABORATORS_REQUEST = 'GET_COLLABORATORS_REQUEST';
export const GET_COLLABORATORS_FAILURE = 'GET_COLLABORATORS_FAILURE';
export const GET_COLLABORATORS_SUCCESS = 'GET_COLLABORATORS_SUCCESS';

export const GET_MEMBERS_REQUEST = 'GET_MEMBERS_REQUEST';
export const GET_MEMBERS_FAILURE = 'GET_MEMBERS_FAILURE';
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';

export const GET_COWORKERS_REQUEST = 'GET_COWORKERS_REQUEST';
export const GET_COWORKERS_FAILURE = 'GET_COWORKERS_FAILURE';
export const GET_COWORKERS_SUCCESS = 'GET_COWORKERS_SUCCESS';

export const UPDATE_ORGANIZATION_REQUEST = 'UPDATE_ORGANIZATION_REQUEST';
export const UPDATE_ORGANIZATION_FAILURE = 'UPDATE_ORGANIZATION_FAILURE';
export const UPDATE_ORGANIZATION_SUCCESS = 'UPDATE_ORGANIZATION_SUCCESS';

export const PATCH_COLLABORATOR_REQUEST = 'PATCH_COLLABORATOR_REQUEST';
export const PATCH_COLLABORATOR_SUCCESS = 'PATCH_COLLABORATOR_SUCCESS';
export const PATCH_COLLABORATOR_FAILURE = 'PATCH_COLLABORATOR_FAILURE';

export const STATUSES = {
    CANCELED: 'canceled',
    CHURNED: 'churned',
    DELINQUENT: 'delinquent',
    TRIAL_EXPIRED: 'trial-expired',
    PAYING: 'paying',
    EXPIRED: 'expired',
};

export const PLANS = {
    TRIAL: 'trial',
    MIRROR_TRIAL: 'mirror-trial',
    CUSTOM_INVOICED: 'custom-invoiced',
    FREE_WITH_WRIKE: 'reseller-wrike',
};

export const EDIT_ORG_NAME_FORM = 'EDIT_ORG_NAME_FORM';
export const EDIT_ORG_BILLING_EMAIL_FORM = 'EDIT_ORG_BILLING_EMAIL_FORM';
export const EDIT_ORG_SEND_EMAIL_RECEIPT_FORM = 'EDIT_ORG_SEND_EMAIL_RECEIPT_FORM';

export const PEOPLE_TYPES = {
    MEMBER: 'member',
    COWORKER: 'coworker',
};

export const EVENTS = {
    USER_CLICKED_BILLING_INTERVAL: 'USER_CLICKED_BILLING_INTERVAL',
    USER_CLICKED_SELECT_PLAN: 'USER_CLICKED_SELECT_PLAN',
    USER_CLICKED_CANCEL_SUBSCRIPTION: 'USER_CLICKED_CANCEL_SUBSCRIPTION',
    USER_CLICKED_CHANGE_CARD: 'USER_CLICKED_CHANGE_CARD',
    USER_PLAN_CHANGE_BLOCKED: 'USER_PLAN_CHANGE_BLOCKED',
    USER_PLAN_SELECTION_BLOCKED: 'USER_PLAN_SELECTION_BLOCKED',
    USER_CHANGED_PLAN: 'USER_CHANGED_PLAN',
    USER_PURCHASED_PLAN: 'USER_PURCHASED_PLAN',
    USER_CLICKED_FAILED_PAYMENT_BANNER: 'USER_CLICKED_FAILED_PAYMENT_BANNER',
    USER_CLICKED_BLOCKED_AUTO_SYNC_BANNER: 'USER_CLICKED_BLOCKED_AUTO_SYNC_BANNER',
    USER_CLICKED_BILLING_HEADER_MENU_UPGRADE_NOW: 'USER_CLICKED_HEADER_MENU_UPGRADE_NOW',
    USER_CLICKED_BILLING_GAUGE_UPGRADE_NOW: 'USER_CLICKED_HEADER_GAUGE_UPGRADE_NOW',
    USER_CLICKED_BILLING_GAUGE_SEE_DETAILS: 'USER_CLICKED_HEADER_GAUGE_SEE_DETAILS',
    USER_CLICKED_BILLING_EXPERIMENT_1: 'USER_CLICKED_UPGRADE_BANNER',
    USER_CLICKED_UPGRADE_NOW_ADD_SYNC_BLOCKED: 'USER_CLICKED_UPGRADE_NOW_ADD_SYNC_BLOCKED',
    USER_CLICKED_UPGRADE_NOW_ADD_EDIT_SYNC_BLOCKED: 'USER_CLICKED_UPGRADE_NOW_ADD_EDIT_SYNC_BLOCKED',
    USER_CLICKED_BACK_SYNC_BLOCKED: 'USER_CLICKED_BACK_TO_DASHBOARD_SYNC_BLOCKED',
    USER_SAW_ADD_SYNC_BLOCKED: 'USER_SAW_ADD_SYNC_BLOCKED',
    USER_SAW_ADD_EDIT_SYNC_BLOCKED: 'USER_SAW_ADD_EDIT_SYNC_BLOCKED',
    USER_SAW_BILLING_EXPERIMENT_1: 'USER_SAW_UPGRADE_BANNER',
    USER_SAW_FAILED_PAYMENT_BANNER: 'USER_SAW_FAILED_PAYMENT_BANNER',
    USER_SAW_BLOCKED_AUTOSYNC: 'USER_SAW_BLOCKED_AUTOSYNC',
};



// WEBPACK FOOTER //
// ./src/consts/organizations.js