export const GET_PROVIDER_IDENTITY_REQUEST = 'GET_PROVIDER_IDENTITY_REQUEST';
export const GET_PROVIDER_IDENTITY_SUCCESS = 'GET_PROVIDER_IDENTITY_SUCCESS';
export const GET_PROVIDER_IDENTITY_FAILURE = 'GET_PROVIDER_IDENTITY_FAILURE';
export const GET_PROVIDER_IDENTITIES_REQUEST = 'GET_PROVIDER_IDENTITIES_REQUEST';
export const GET_PROVIDER_IDENTITIES_SUCCESS = 'GET_PROVIDER_IDENTITIES_SUCCESS';
export const GET_PROVIDER_IDENTITIES_FAILURE = 'GET_PROVIDER_IDENTITIES_FAILURE';
export const VALIDATE_PROVIDER_IDENTITY_REQUEST = 'VALIDATE_PROVIDER_IDENTITY_REQUEST';
export const VALIDATE_PROVIDER_IDENTITY_SUCCESS = 'VALIDATE_PROVIDER_IDENTITY_SUCCESS';
export const VALIDATE_PROVIDER_IDENTITY_FAILURE = 'VALIDATE_PROVIDER_IDENTITY_FAILURE';
export const DISCONNECT_PROVIDER_IDENTITY_REQUEST = 'DISCONNECT_PROVIDER_IDENTITY_REQUEST';
export const DISCONNECT_PROVIDER_IDENTITY_SUCCESS = 'DISCONNECT_PROVIDER_IDENTITY_SUCCESS';
export const DISCONNECT_PROVIDER_IDENTITY_FAILURE = 'DISCONNECT_PROVIDER_IDENTITY_FAILURE';
export const GET_ALLOWED_PROVIDER_IDENTITIES_REQUEST = 'GET_ALLOWED_PROVIDER_IDENTITIES_REQUEST';
export const GET_ALLOWED_PROVIDER_IDENTITIES_SUCCESS = 'GET_ALLOWED_PROVIDER_IDENTITIES_SUCCESS';
export const GET_ALLOWED_PROVIDER_IDENTITIES_FAILURE = 'GET_ALLOWED_PROVIDER_IDENTITIES_FAILURE';
export const REACTIVATE_SINGLE_PROVIDER_IDENTITY = 'REACTIVATE_SINGLE_PROVIDER_IDENTITY';

export const STATE = {
    DISABLED: 'disabled',
    ACTIVE: 'active',
};



// WEBPACK FOOTER //
// ./src/consts/providerIdentity.js