export const FORM_ACTIONS = {
    START: 'START',
    NEXT: 'NEXT',
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    BACK: 'BACK',
    CANCEL: 'CANCEL',
    SUBMIT: 'SUBMIT',
    SAVE: 'SAVE',
    WARNING: 'WARNING',
    DENIED: 'DENIED',
};

export const WELCOME_ACTIONS = {
    SKIP: 'SKIP',
    START: 'START',
    END: 'END',
};

export const UNITO_TRACKING = '@@unitoTracking/';
export const TRACK = 'TRACK';
export const TRACK_ANON = 'TRACK_ANON';

export const AUTH_SETUP = {
    USER_OAUTH_START: 'USER_OAUTH_START',
    USER_OAUTH_ENTER_URL_NEXT: 'USER_OAUTH_ENTER_URL_NEXT',
    USER_OAUTH_ENTER_URL_FAILURE: 'USER_OAUTH_ENTER_URL_FAILURE',
    USER_OAUTH_SUBMIT: 'USER_OAUTH_SUBMIT',
    USER_OAUTH_FAILURE: 'USER_OAUTH_FAILURE',
    USER_OAUTH_CHOOSE_METHOD_NEXT: 'USER_OAUTH_CHOOSE_METHOD_NEXT',
    USER_OAUTH_CHOOSE_METHOD_FAILURE: 'USER_OAUTH_CHOOSE_METHOD_FAILURE',
    USER_OAUTH_CHOOSE_METHOD_CANCEL: 'USER_OAUTH_CHOOSE_METHOD_CANCEL',
    USER_OAUTH_ENTER_URL_CANCEL: 'USER_OAUTH_ENTER_URL_CANCEL',
};

export const HUBSPOT_BETA = {
    USER_HUBSPOT_DEALS_CLICK: 'USER_HUBSPOT_DEALS_CLICK',
    USER_HUBSPOT_DEALS_NOTIFY_ME: 'USER_HUBSPOT_DEALS_NOTIFY_ME',
    USER_HUBSPOT_DEALS_DONT_NOTIFY_ME: 'USER_HUBSPOT_DEALS_DONT_NOTIFY_ME',
};



// WEBPACK FOOTER //
// ./src/consts/tracking.js